/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Provides XML serialization and parsing support for OAObject graphs, Hubs, and
 * lightweight XML name/value structures.  
 *
 * <p>This package contains two distinct generations of XML tooling:</p>
 *
 * <h2>1. Legacy OA-XML Format (Pre-OAJson)</h2>
 * <p>
 * These classes implement a full round-trip XML serialization system for OAObjects,
 * including identity preservation, cascaded link traversal, import-matching rules,
 * hub expansion, property conversion, and GUID mapping.
 * </p>
 *
 * <ul>
 *   <li>{@link com.viaoa.xml.OAXMLWriter OAXMLWriter}  
 *       Serializes OAObjects and Hubs into an XML representation that preserves
 *       object identity, owned-by relationships, link properties, and data cascades.
 *       Supports encrypted CDATA payloads and multiple write-modes (full object,
 *       key-only, suppress-new, etc.).</li>
 *
 *   <li>{@link com.viaoa.xml.OAXMLReader OAXMLReader}  
 *       Parses XML generated by {@code OAXMLWriter}, reconstructing OAObject instances
 *       using a two-pass GUID and key-matching algorithm. Supports import-matching,
 *       property conversion, nested hubs, polymorphic classes, and legacy
 *       OAXMLReader1 compatibility.</li>
 *
 *   <li>{@link com.viaoa.xml.OAXMLReader1 OAXMLReader1}  
 *       Older v1 reader supporting the first-generation OAXML format.  
 *       Automatically engaged when version="1.x" is detected.</li>
 * </ul>
 *
 * <h2>2. Simple XML Parsing</h2>
 * <p>
 * For non-OA data (schemas, configs, metadata), this package includes a very small
 * SAX-based utility:
 * </p>
 *
 * <ul>
 *   <li>{@link com.viaoa.xml.SimpleXMLReader SimpleXMLReader}  
 *       Produces a lightweight tree of nodes containing tag names, attributes, text,
 *       and hierarchical children. Useful for integrating XML resources without
 *       OAObject involvement.</li>
 * </ul>
 *
 * <h2>Design Characteristics</h2>
 * <ul>
 *   <li><b>No reflection for property assignment.</b> All writes go through the
 *       OAObject metadata layer (OAObjectInfo, OALinkInfo, OAPropertyInfo).</li>
 *   <li><b>Identity-safe reconstruction.</b> GUID, ID, and import-match values are
 *       resolved through OAObjectCacheDelegate and OASelect.</li>
 *   <li><b>Two-phase loading.</b> Preload phase resolves references; load phase sets
 *       values and relationships.</li>
 *   <li><b>Recursive hub population.</b> Many-side links are expanded into Hubs and
 *       reattached to their owners.</li>
 *   <li><b>Encryption support.</b> OAXMLWriter can Base64-encode CDATA using
 *       developer-supplied keys; OAXMLReader reverses the process.</li>
 *   <li><b>Deprecated in OA 4.0.</b> All core XML IO is now superseded by
 *       {@code OAXml} (Jackson-based serialization).</li>
 * </ul>
 *
 * <h2>Usage Notes</h2>
 * <p>
 * The XML system remains fully functional for backward compatibility, import tools,
 * and cross-environment migrations, but new code should use:
 * <br><b>{@code com.viaoa.xml.OAXml}</b>  
 * which leverages OAJson and the Jackson engine for modern serialization,
 * streaming, and schema evolution.
 * </p>
 */
package com.viaoa.xml;